name: thinkstrike_frontend
description: A new Flutter project for ThinkStrike (Android + Web)
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  shared_preferences: ^2.0.15
  provider: ^6.0.5
  go_router: ^6.5.0
  fl_chart: ^0.36.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
